export const ADD_TODO = 'containers/TodoPage/ADD_TODO'
export const TOGGLE_TODO = 'containers/TodoPage/TOGGLE_TODO'
export const REMOVE_TODO = 'containers/TodoPage/REMOVE_TODO'
export const CHANGE_FILTER = 'containers/TodoPage/CHANGE_FILTER'
export const FETCH_TODOS = 'containers/TodoPage/FETCH_TODOS'
export const TODOS_FETCHED = 'containers/TodoPage/TODOS_FETCHED'

export const FILTER_ALL = 'containers/TodoPage/FILTER_ALL'
export const FILTER_ACTIVE = 'containers/TodoPage/FILTER_ACTIVE'
export const FILTER_COMPLETED = 'containers/TodoPage/FILTER_COMPLETED'
